# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "034a667f0e8be13bab5101a5878bc966"
name = "ecommind-app-dev"
handle = "ecommind-app-dev"
application_url = "https://shore-brave-sequences-dealing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "new-snowboard-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://shore-brave-sequences-dealing.trycloudflare.com/auth/callback",
  "https://shore-brave-sequences-dealing.trycloudflare.com/auth/shopify/callback",
  "https://shore-brave-sequences-dealing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
