# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3a7c9ef9793e7baf3033f119e6aca902"
name = "SalesMateApp"
handle = "salesmateapp"
application_url = "https://rpm-answering-oo-experiencing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-49562075.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rpm-answering-oo-experiencing.trycloudflare.com/auth/callback",
  "https://rpm-answering-oo-experiencing.trycloudflare.com/auth/shopify/callback",
  "https://rpm-answering-oo-experiencing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
